### PR TITLE
Deploy to Production (28th Nov 2021)

### PR DESCRIPTION
**Pull request by saenyakorn**
## Why did you create this PR
- 

## What did you do
- 

## Demo
[https://beta.cugetreg.com](https://beta.cugetreg.com)

## Checklist
- [ ] Deploy a demo
- [ ] Check browsers compatibility
- [ ] Wrote coverage tests

### CODE REVIEW

**Review by paphonb — APPROVED** [review]
My changes look fine (footer stuffs)

**Comment by paphonb** [comment]
Requesting review from other authors

**Review by bombnp — APPROVED** [review]
Mine works as well

**Comment by Anon-136** [comment]
My migration is fine (it did build, so yeah)

**Pull request merged**
