### PR TITLE
Fix schedule page crash

### PR DESCRIPTION
**Pull request by paphonb**
## Why did you create this PR
- 

## What did you do
- 

## Demo
[https://dev.cugetreg.com](https://dev.cugetreg.com)

## Checklist
- [ ] Deploy a demo
- [ ] Check browsers compatibility
- [ ] Wrote coverage tests

### CODE REVIEW

**Comment by saengowp** [comment]
I tried replicating his course cart but can't reproduce the error. Do you have a test case for me to reproduce it?

**Comment by paphonb** [comment]
@saengowp Try adding 2304104 sec 1 and 2900151 for 2565/1.

**Comment by paphonb** [comment]
> image
> 
> @paphonb it's still dead

Oops! Forgot to push to dev. Can you try again after build?

**Review by bombnp — APPROVED** [review]
yea it works

**Pull request merged**
